In [13]:
import os
import time
import pandas as pd
from PIL import Image
import numpy as np
from scipy.ndimage import convolve
from skimage.color import rgb2gray
from graphConstructor import get_neighbors, sobel_filters, construct_graph_with_gradients

def process_images(folder_path):
    results = []

    for filename in os.listdir(folder_path):
        if filename.endswith(('.png', '.jpg', '.jpeg','.bmp')):
            image_path = os.path.join(folder_path, filename)
            image = np.array(Image.open(image_path).convert('L'))

            start_time = time.time()

            # Apply Sobel filters and construct graph
            Gx, Gy, G = sobel_filters(image)
            filter_end_time= time.time()-start_time
            start_time = time.time()
            graph = construct_graph_with_gradients(image, G)
            time_taken = time.time() - start_time

            # Record the results
            results.append({
                'Image Name': filename,
                'Shape': image.shape,
                'Filter Time': filter_end_time,
                'Graph Time': time_taken,
            })

    return pd.DataFrame(results)

folder_path = 'images' 
result_table = process_images(folder_path)
print(result_table)


KeyboardInterrupt: 

In [5]:
import sys
print(sys.path)

# from graphEnergy import  energy_filter, construct_graph_with_gradients
# simple test with standard graph to show that the filter works
image = np.array([[ 57, 119, 242,  99, 120,  38,  89],
 [  3, 100, 210, 165, 186, 251, 255],
 [ 26, 125,   7, 178, 198, 154, 254],
 [193, 187, 251,  83,  98, 212,  61],
 [ 21,  99, 220, 237,  77, 205, 193],
 [ 31, 238,  96, 143, 190,  39,   4],
 [ 19, 201, 189,  19,  40,  18,  17]]) 
image2= np.array(
  [[10,20,51,61],[41,94,12,55],[52,22,31,81],[12,43, 68,30]]
)
Gx, Gy,G = sobel_filters(image2)
print("Gx (Gradient in x-direction):\n", Gx)
print("\nGy (Gradient in y-direction):\n", Gy)
print("\nG (Gradient Magnitude):\n", G)


['/Users/kevin/Library/CloudStorage/OneDrive-UBC/school/2023 fall/520/COSC_520/testSuite1', '/Library/Frameworks/Python.framework/Versions/3.8/lib/python38.zip', '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8', '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload', '', '/Users/kevin/Library/CloudStorage/OneDrive-UBC/school/2023 fall/520/520/lib/python3.8/site-packages']
Gx (Gradient in x-direction):
 [[ -83  -94  -84  -73]
 [ -86   38  -22 -146]
 [ -24   15  -66 -105]
 [ -63 -147  -20   64]]

Gy (Gradient in y-direction):
 [[-167 -140   10   57]
 [-128  -26   18  -40]
 [ 138   75  -36   19]
 [  99  -39  -44  116]]

G (Gradient Magnitude):
 [[186.48860555 168.62977199  84.59314393  92.61749295]
 [154.20765221  46.04345773  28.42534081 151.38031576]
 [140.07141036  76.4852927   75.17978452 106.70520137]
 [117.34564329 152.08550227  48.33218389 132.48396129]]
